### ISSUE TITLE
Possible to omit unused links, meta, relationships

### ISSUE THREAD

**Issue by bradbyte** [cludden/json-api-ify#29]
Hello,

Thank you for this library! it's taking awhile to find one that met my use cases. Was spoiled with Google's jsonapi for Go. Is it possible to omit the attributes of `links`, `meta`, and `relationships` if there isn't any data set on them? so instead of rendering an empty bracket, it wouldn't exist. If it's not possible, would you be ok with a PR to add this? It would probably me an option on the serializer if you want to omit it.

Thanks!

-Brad

**Comment by cludden** [comment]
@bradbumbalough sorry I never saw this issue, i would gladly accept a PR! I've been busy working on another JSON API project that is a bit more low level but supports the full spec and omits empty sections, check it out [transformalizer](https://github.com/GaiamTV/transformalizer)
