### ISSUE TITLE
question: Included for unpopulated relationships

### ISSUE THREAD

**Issue by danivek** [cludden/json-api-ify#9]
If we declare `include: true` on a relationship and have data with unpopulated relationship (id, array of ids or object with just the id property) for this one, does it make sense to have it in `included` with empty attributes ?

**Comment by cludden** [comment]
I tend to agree that it does not make sense to "include" anything if the relationship is not populated. Will update that shortly.

**Comment by danivek** [comment]
Thanks @cludden
Awesome library.

**Comment by cludden** [comment]
No prob @danivek, thanks for your help!
